#!/usr/bin/env python3
"""Map gallery: every pool map placed side by side in the arena dimension with floating labels, so the user can
walk through them in-game (`/function <ns>:gallery/build`, then `/function <ns>:gallery/tp`).

build_pack.py calls write_functions() for every build (project.json "gallery": true). This CLI rebuilds the
project and, with --check, boots a test server, runs the gallery build and verifies every map and label.

Usage:
    python tools/mapgen/gallery.py <project-dir> [--check]
"""
import argparse
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)


def layout(project, maps, cfg):
    """-> list of (map_id, origin_x, origin_y, origin_z) along +x from config gallery.origin."""
    gx, gy, gz = cfg["gallery"]["origin"]
    x = gx
    out = []
    for mid, m in maps.items():
        out.append((mid, x, gy, gz))
        x += m["size"][0] + cfg["gallery"]["spacing"]
    return out


def write_functions(out, ns, project, maps, cfg):
    dim = f"{ns}:{project['arena']['dimension']}"
    lay = layout(project, maps, cfg)
    lines = ["# generated by tools/mapgen/gallery.py: place every pool map side by side with labels",
             f"execute in {dim} run kill @e[type=minecraft:text_display,tag={ns}.gallery]"]
    lh = cfg["gallery"]["label_height"]
    for mid, x, y, z in lay:
        m = maps[mid]
        sx, sy, sz = m["size"]
        lines.append(f"execute in {dim} run forceload add {x} {z} {x + sx - 1} {z + sz - 1}")
        for t in m["tiles"]:
            ox, oy, oz = m["origin"]["x"], m["origin"]["y"], m["origin"]["z"]
            lines.append(f"execute in {dim} run place template {t['t']} {x + t['x'] - ox} {y + t['y'] - oy} {z + t['z'] - oz}")
        cx = x + sx // 2
        rows = [m["name"], "tags: " + ", ".join(m["tags"]),
                f"players {m['players']['min']}-{m['players']['max']}  size {sx}x{sy}x{sz}"]
        for i, text in enumerate(rows):
            safe = text.replace("\\", "/").replace('"', "'")
            color = "gold" if i == 0 else "white"
            lines.append(f"execute in {dim} run summon minecraft:text_display {cx} {y + sy + lh - i * 0.4:.1f} {z - 1} "
                         f"{{Tags:[\"{ns}.gallery\"],billboard:\"center\",text:{{text:\"{safe}\",color:\"{color}\"}}}}")
    lines.append(f"tellraw @a {{text:\"[{ns}] gallery built: {len(lay)} map(s)\",color:\"green\"}}")
    fdir = os.path.join(out, "data", ns, "function", "gallery")
    os.makedirs(fdir, exist_ok=True)
    with open(os.path.join(fdir, "build.mcfunction"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    if lay:
        mid, x, y, z = lay[0]
        with open(os.path.join(fdir, "tp.mcfunction"), "w", encoding="utf-8", newline="\n") as f:
            f.write("# generated: teleport @s to the start of the gallery (run as a player)\n"
                    f"execute in {dim} run tp @s {x - 4} {y + maps[mid]['size'][1] + 2} {z - 6} -45 30\n")
    return lay


def main():
    sys.path.insert(0, os.path.dirname(HERE))
    import build_pack
    import core
    import run_tests as rt
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("project")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    try:
        out = build_pack.build(args.project)
    except core.MapgenError as e:
        print(f"FAIL: {e}")
        return 1
    if not args.check:
        return 0
    import json
    import re
    ns = json.load(open(os.path.join(args.project, "project.json"), encoding="utf-8"))["namespace"]
    reg = open(os.path.join(out, "data", ns, "function", "_gen", "registry.mcfunction"), encoding="utf-8").read()
    n_maps = len(re.findall(r"registry maps\.\w+ set value", reg))
    server = rt.Server(out)
    server.prepare()
    if not server.start():
        print("FAIL: server did not start")
        server.stop()
        return 1
    try:
        resp = server.rcon.cmd(f"function {ns}:gallery/build")
        time.sleep(0.5)
        labels = server.rcon.cmd(f"execute if entity @e[type=minecraft:text_display,tag={ns}.gallery]")
        errs = rt.datapack_errors(server.log_since(0))
        print(f"gallery/build -> {resp!r}\nlabels -> {labels!r}")
        ok = f"Count: {n_maps * 3}" in labels and not errs
        for b in errs:
            print("   " + " | ".join(b))
    finally:
        server.stop()
    print(f"RESULT: {'PASS' if ok else 'FAIL'} ({n_maps} map(s), expected {n_maps * 3} labels)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
