#!/usr/bin/env python3
"""Generate library/INDEX.md from the header comments of the public library functions.

Usage: python tools/gen_library_index.py [--check] [--lib DIR]

Public = every .mcfunction under data/mcdp_lib/function/ except _internal/. Each must start with:
    #> mcdp_lib:<path>          (must match the file)
    #> Purpose: ...   #> Inputs: ...   #> Outputs: ...   #> Effects: ...
    #> Context: ...   #> Cost: ...     #> Example: ...
Every $(name) used in the file must be mentioned in the Inputs line.
Exit 1 (and no file written) if any public function breaks these rules. --check: also exit 1 if INDEX.md is stale.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIELDS = ["Purpose", "Inputs", "Outputs", "Effects", "Context", "Cost", "Example"]


def parse(path, fid):
    lines = open(path, encoding="utf-8").read().split("\n")
    head = [l[2:].strip() for l in lines if l.startswith("#>")]
    errs = []
    if not head or head[0] != fid:
        errs.append(f"first header line must be '#> {fid}'")
    info = {}
    for h in head[1:]:
        m = re.match(r"([A-Za-z]+):\s*(.*)", h)
        if m:
            info[m.group(1)] = m.group(2)
    for f in FIELDS:
        if not info.get(f):
            errs.append(f"missing '#> {f}: ...'")
    used = set(re.findall(r"\$\(([A-Za-z0-9_]+)\)", "\n".join(l for l in lines if l.startswith("$"))))
    for name in sorted(used):
        if not re.search(r"\b" + name + r"\b", info.get("Inputs", "")):
            errs.append(f"macro argument '{name}' is not documented in Inputs")
    info["_macro"] = sorted(used)
    return info, errs


def signature(info):
    if info["_macro"]:
        return "{" + ", ".join(info["_macro"]) + "}"
    return "(no macro args)"


def main(argv):
    lib = os.path.join(ROOT, "library", "mcdp_lib")
    if "--lib" in argv:
        lib = os.path.abspath(argv[argv.index("--lib") + 1])
    fdir = os.path.join(lib, "data", "mcdp_lib", "function")
    entries, problems = [], []
    for dp, dns, fns in os.walk(fdir):
        dns[:] = sorted(d for d in dns if d != "_internal")
        for fn in sorted(fns):
            if not fn.endswith(".mcfunction"):
                continue
            rel = os.path.relpath(os.path.join(dp, fn), fdir).replace(os.sep, "/")[:-len(".mcfunction")]
            fid = "mcdp_lib:" + rel
            info, errs = parse(os.path.join(dp, fn), fid)
            problems += [f"{fid}: {e}" for e in errs]
            entries.append((rel.split("/")[0] if "/" in rel else "(root)", fid, info))
    if problems:
        print("\n".join("ERROR " + p for p in problems))
        print(f"gen_library_index: FAIL ({len(problems)} problem(s)); INDEX.md not written")
        return 1
    out = ["# mcdp_lib function index (generated by tools/gen_library_index.py; do not edit)", "",
           "Search this before writing a new function. Call as `function mcdp_lib:<path> {args}` (macro) or set the",
           "listed inputs first. Full contract (outputs, side effects, context, example) is in each file's header.",
           "Conventions: inputs `mcdp_lib:in` storage / `mcdp_lib.in` scores, outputs `mcdp_lib:out` / `#result mcdp_lib.out`",
           "and the function's return value; `fast` = no macro (safe per tick); never call `_internal/` functions.", ""]
    cat = None
    for c, fid, info in sorted(entries, key=lambda e: (e[0], e[1])):
        if c != cat:
            cat = c
            out += ["", f"## {c}"]
        fast = " **fast**" if info["Cost"].startswith("fast") else ""
        out.append(f"- `{fid}` `{signature(info)}`{fast} - {info['Purpose']}")
    text = "\n".join(out).replace("\n\n\n", "\n\n") + "\n"
    dest = os.path.join(os.path.dirname(lib), "INDEX.md")
    if "--check" in argv:
        old = open(dest, encoding="utf-8").read() if os.path.exists(dest) else ""
        if old != text:
            print("gen_library_index: INDEX.md is stale; run python tools/gen_library_index.py")
            return 1
        print(f"gen_library_index: OK ({len(entries)} public functions, INDEX.md up to date)")
        return 0
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"gen_library_index: wrote {os.path.relpath(dest, ROOT)} ({len(entries)} public functions)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
